 * Serving Flask app "yeetcode.py" (lazy loading)
 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "/home/brandon/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [25/May/2020 14:56:33] "[37mPOST /judge HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 14:56:35] "[37mPOST /judge HTTP/1.1[0m" 200 -
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "yeetcode", an ImportError was raised:

Traceback (most recent call last):
  File "/home/brandon/.local/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/yeetcode.py", line 1, in <module>
    from app import create_app, db
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/app/__init__.py", line 9, in <module>
    import rq
ModuleNotFoundError: No module named 'rq'

 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "yeetcode.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [25/May/2020 17:19:08] "[37mGET /homepage HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:08] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:08] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:08] "[37mGET /static/images/codeimage.jpg HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:08] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:08] "[37mGET /static/Lato/Lato-Light.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:09] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:13] "[37mGET /static/images/interviewimage.jpg HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:28] "[37mGET /problems HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:29] "[37mGET /rankings HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:29] "[33mGET /static/admin/Lato/Lato-Bold.ttf HTTP/1.1[0m" 404 -
127.0.0.1 - - [25/May/2020 17:19:29] "[33mGET /static/admin/Lato/Lato-Light.ttf HTTP/1.1[0m" 404 -
127.0.0.1 - - [25/May/2020 17:19:30] "[37mGET /admin/manage HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:30] "[33mGET /static/admin/Lato/Lato-Bold.ttf HTTP/1.1[0m" 404 -
127.0.0.1 - - [25/May/2020 17:19:30] "[37mPOST /api/tokens HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:31] "[37mGET /homepage HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:37] "[37mGET /problems HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:38] "[37mGET /problem/aminusb HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:19:38] "[37mPOST /api/tokens HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:23:01] "[32mGET /logout HTTP/1.1[0m" 302 -
127.0.0.1 - - [25/May/2020 17:23:01] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:23:01] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
[2020-05-25 17:23:03,714] ERROR in app: Exception on /problems [GET]
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/app/problems/routes.py", line 17, in problems
    problemscompleted = ProblemsCompleted.query.filter_by(userID=current_user.id)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
127.0.0.1 - - [25/May/2020 17:23:03] "[35m[1mGET /problems HTTP/1.1[0m" 500 -
[2020-05-25 17:23:20,343] ERROR in app: Exception on /problems [GET]
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/app/problems/routes.py", line 17, in problems
    problemscompleted = ProblemsCompleted.query.filter_by(userID=current_user.id)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
127.0.0.1 - - [25/May/2020 17:23:20] "[35m[1mGET /problems HTTP/1.1[0m" 500 -
 * Serving Flask app "yeetcode.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 207-675-622
127.0.0.1 - - [25/May/2020 17:23:52] "[35m[1mGET /problems HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/app/problems/routes.py", line 17, in problems
    problemscompleted = ProblemsCompleted.query.filter_by(userID=current_user.id)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
127.0.0.1 - - [25/May/2020 17:23:52] "[37mGET /problems?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:23:52] "[37mGET /problems?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:23:52] "[37mGET /problems?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:23:52] "[37mGET /problems?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:23:52] "[37mGET /problems?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:23:52] "[37mGET /problems?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Detected change in '/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/app/problems/routes.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 207-675-622
 * Serving Flask app "yeetcode.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 207-675-622
127.0.0.1 - - [25/May/2020 17:26:06] "[35m[1mGET /problems HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/yeetcode.py", line 5, in <module>
    app = create_app()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/app/__init__.py", line 56, in create_app
    from app.problems import bp as problems_bp
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/app/problems/__init__.py", line 5, in <module>
    from app.problems import routes
File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/app/problems/routes.py", line 17
    status = {}
    ^
IndentationError: unexpected indent
127.0.0.1 - - [25/May/2020 17:26:06] "[37mGET /problems?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:26:06] "[37mGET /problems?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:26:07] "[37mGET /problems?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:26:07] "[37mGET /problems?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:26:07] "[37mGET /problems?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:26:07] "[37mGET /problems?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Serving Flask app "yeetcode.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 207-675-622
127.0.0.1 - - [25/May/2020 17:26:27] "[35m[1mGET /problems HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/app/problems/routes.py", line 19, in problems
    problemscompleted = ProblemsCompleted.query.filter_by(userID=current_user.id)
  File "/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
127.0.0.1 - - [25/May/2020 17:26:27] "[37mGET /problems?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:26:27] "[37mGET /problems?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:26:27] "[37mGET /problems?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:26:27] "[37mGET /problems?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:26:27] "[37mGET /problems?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:26:27] "[37mGET /problems?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Detected change in '/home/brandon/OneDrive/Stuff/Documents/cits3403/CITS3403-Project-2/app/problems/routes.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 207-675-622
 * Serving Flask app "yeetcode.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 207-675-622
127.0.0.1 - - [25/May/2020 17:28:44] "[37mGET /problems HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:28:44] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:28:44] "[37mGET /static/problems/problem.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:28:44] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:28:44] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:28:44] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:28:48] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:28:48] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:28:52] "[32mPOST /login HTTP/1.1[0m" 302 -
127.0.0.1 - - [25/May/2020 17:28:52] "[37mGET /homepage HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:28:53] "[37mGET /problems HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:31:40] "[37mGET /problem/problemfiller2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:31:40] "[37mPOST /api/tokens HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:31:43] "[37mPOST /judge HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:32:00] "[37mPOST /judge HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:32:09] "[37mGET /problems HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:32:09] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:32:09] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:32:09] "[37mGET /static/problems/problem.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:32:09] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:32:09] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:32:27] "[37mGET /problems HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:32:32] "[37mGET /rankings HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:32:32] "[33mGET /static/admin/Lato/Lato-Bold.ttf HTTP/1.1[0m" 404 -
127.0.0.1 - - [25/May/2020 17:32:32] "[33mGET /static/admin/Lato/Lato-Light.ttf HTTP/1.1[0m" 404 -
127.0.0.1 - - [25/May/2020 17:32:34] "[37mGET /profile/yeezy/1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:32:37] "[37mGET /problems HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:32:38] "[37mGET /homepage HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:33:01] "[32mGET /logout HTTP/1.1[0m" 302 -
127.0.0.1 - - [25/May/2020 17:33:01] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:40] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:40] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:40] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:40] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:40] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:40] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:40] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:40] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:41] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:41] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:41] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:41] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:41] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:34:41] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:13] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:13] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:13] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:13] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:13] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:13] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:13] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:37] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:37] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:37] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:37] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:37] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:37] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:37] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:58] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:58] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:58] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:58] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:58] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:59] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:35:59] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:36:24] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:36:51] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:36:51] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:36:51] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:36:51] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:36:51] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:36:52] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:36:52] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:37:23] "[37mGET /register HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:37:50] "[37mGET /register HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:37:50] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:37:50] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:37:50] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:37:50] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:37:51] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:37:51] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:27] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:27] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:27] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:27] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:27] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:28] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:28] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:51] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:51] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:51] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:51] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:51] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:52] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:52] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:55] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:56] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:56] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:56] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:56] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:56] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:39:56] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:15] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:15] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:15] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:15] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:15] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:16] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:16] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:22] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:22] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:22] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:22] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:22] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:22] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:22] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:40] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:40] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:40] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:40] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:40] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:41] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:41] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:56] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:57] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:57] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:57] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:57] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:57] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:40:57] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:41:02] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:41:03] "[37mGET /register HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:41:26] "[37mGET /register HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:41:26] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:41:26] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:41:26] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:41:26] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:41:26] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:41:26] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:03] "[37mGET /register HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:03] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:03] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:03] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:03] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:04] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:04] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:28] "[37mGET /register HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:28] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:28] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:28] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:28] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:28] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:28] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:34] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:41] "[37mGET /login HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:41] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:41] "[37mGET /static/auth/login-register.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:41] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:41] "[37mGET /static/auth/login-register.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:41] "[37mGET /static/Lato/Lato-Bold.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:41] "[37mGET /static/favicon/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:43] "[37mGET /register HTTP/1.1[0m" 200 -
127.0.0.1 - - [25/May/2020 17:42:47] "[37mGET /homepage HTTP/1.1[0m" 200 -
